name: fetch
on:
  schedule:
    - cron: '53 */6 * * *'
  workflow_dispatch:

jobs:
  get:
    runs-on: ubuntu-latest

    steps:
      - name: get latest
        run: curl https://games-gallery.jacobcarpenter.com/latest
